apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-ssr-website
  description: test ssr website
  annotations:
    github.com/project-slug: soapraj/test-ssr-website
    backstage.io/techdocs-ref: github:https://github.com/soapraj/test-ssr-website
spec:
  type: website
  lifecycle: experimental
  owner: soapraj
